name: Cypress Tests

on: 
  push:
    branches:
      - main

jobs:
  cypress-run:
    strategy:
      fail-fast: false #debuggin param - turn off before deploying to prod
      matrix:
        #os: [ubuntu-latest, macos-latest, windows-latest]
        browsers: [firefox, chrome, edge]
    runs-on: ubuntu-22.04

    steps:
    ## Checkout a Git repository at a particular version under $GITHUB_WORKSPACE,
    # so your workflow can access it
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 #only will use last commit 
      
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: get node version
        run: node -v

      - name: Cypress run
        uses: cypress-io/github-action@v5 # use the exaplicit version number for this action
        with:                             
          #browser: ${{ matrix.browsers }}
          build: npm install verbose
          # start: npm run cypress:run
          run: npm run cypress:run --browser ${{ matrix.browsers }

      - name: artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test reports
          path: /home/runner/work/cypress-cucumber-pageobject-demo/cypress-cucumber-pageobject-demo/cypress/reports
      